[tool.poetry]
name = "python-fdda"
version = "0.1.0"
description = "Frequency Domain Data Augmentation in Python"
authors = ["Michael Verdegaal <michaelverdegaal@hotmail.nl>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.1.1"

[tool.commitizen]
version = "0.2.0"
update_changelog_on_bump = true
major_version_zero = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
